openapi: 3.0.0
info:
  title: API сервер для проекта "Шесть городов".
  description: |-
    * Список ресурсов и маршрутов сервера "Шесть городов".
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
  - name: offers
    description: Действия с объявлениями.
  - name: users
    description: Действия с пользователями.
  - name: comments
    description: Действия с комментариями.

paths:
  /offers:
    get:
      tags:
        - offers
      summary: Список предложений
      description: Возвращает список предложений
    post:
      tags:
        - offers
      summary: Публикация предложения
      description: Публикует новое предложения
  /offers/premium:
    get:
      tags:
        - offers
      summary: Список премиальных предложений
      description: Возвращает список премиальных предложений
  /offers/{offerId}:
    get:
      tags:
        - offers
      summary: Полное предложение
      description: Возвращает детальную информацию о предложении
    patch:
      tags:
        - offers
      summary: Обновление предложения
      description: Обновляет информацию о предложении
    delete:
      tags:
        - offers
      summary: Удаление предложения
      description: Удаляет предложение
  /offers/{offerId}/comments:
    get:
      tags:
        - comments
      summary: Список комментариев
      description: Возвращает список комментариев для предложения
    post:
      tags:
        - comments
      summary: Добавление комментария
      description: Добавляет новый комментарий для предложения
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя
  /users/login:
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Вход в закрытую часть приложения. Авторизация на основе логина и пароля
  /users/logout:
    delete:
      tags:
        - users
      summary: Завершение сеанса пользователя
      description: Выход из закрытой части приложения

components:
  schemas:
    offer:
      type: object

      properties:
        title:
          type: string
          example: Nice house
        date:
          type: string
          example: 2024-01-01T12:00:00.000Z
        city:
          $ref: '#/components/schemas/city'
        previewImage:
          type: string
          example: https://url-to-image/image.jpeg
        isPremium:
          type: boolean
          example: false
        isFavorite:
          type: boolean
          example: false
        rating:
          type: number
          format: float
          example: 4.5
        type:
          type: string
          example: house
          enum:
            - house
            - room
            - hotel
            - apartment
        price:
          type: integer
          format: int32
          example: 1000
        commentsNumber:
          type: integer
          format: int32
          example: 12
    fullOffer:
      allOf:
        - $ref: '#/components/schemas/offer'
        - type: object
          properties:
            description:
              type: string
              example: Really nice house. Very comfy
            images:
              type: array
              items:
                type: string
                example: https://url-to-image/image.jpeg
            bedrooms:
              type: integer
              format: int32
              example: 3
            maxGuests:
              type: integer
              format: int32
              example: 4
            goods:
              type: array
              items:
                type: string
                example: Breakfast
                enum:
                  - Breakfast
                  - Air conditioning
                  - Laptop friendly workspace
                  - Baby seat
                  - Washer
                  - Towels
                  - Fridge
            location:
              $ref: '#/components/schemas/location'
    getOffer:
      allOf:
        - $ref: '#/components/schemas/fullOffer'
        - type: object
          properties:
            host:
              $ref: '#/components/schemas/user'
    createOffer:
      allOf:
        - $ref: '#/components/schemas/fullOffer'
        - type: object
          properties:
            hostId:
              type: string
              example: 6329c3d6a04ab1061c6425ea
    location:
      type: object
      properties:
        latitude:
          type: number
          format: float
          example: 52.12345678901234
        longitude:
          type: number
          format: float
          example: 4.12345678901234
    user:
      type: object
      properties:
        name:
          type: string
          example: Tomas
        email:
          type: string
          format: email
          example: tomas@post.go
        avatarUrl:
          type: string
          example: https://url-to-image/image.jpeg
        isPro:
          type: boolean
          example: false
    city:
      type: string
      example: Paris
      enum:
        - Paris
        - Cologne
        - Brussels
        - Amsterdam
        - Hamburg
        - Dusseldorf
